version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - ./github.com/anayaran/hello-world/webapp/target/webapp.war
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
